services:
    terminal42_rootcontent.controller.rootcontent_module:
        class: Terminal42\RootcontentBundle\Controller\RootcontentController
        public: true
        arguments: ["@contao.framework", "@contao.routing.scope_matcher", "@database_connection", "@security.token_storage"]
        tags: [{ name: contao.frontend_module, category: miscellaneous }]

    terminal42_rootcontent.listener.article_operation:
        class: Terminal42\RootcontentBundle\EventListener\ArticleOperationListener
        public: true
        arguments: ["@security.token_storage"]

    terminal42_rootcontent.listener.article_section:
        class: Terminal42\RootcontentBundle\EventListener\ArticleSectionListener
        public: true
        arguments: ["@request_stack", "@database_connection", "@security.token_storage"]

    terminal42_rootcontent.listener.module_field:
        class: Terminal42\RootcontentBundle\EventListener\ModuleFieldListener
        public: true

    terminal42_rootcontent.listener.module_sections:
        class: Terminal42\RootcontentBundle\EventListener\ModuleSectionsListener
        public: true
        arguments: ["@request_stack", "@database_connection"]

    Terminal42\RootcontentBundle\EventListener\RootLimitListener:
        arguments: ["@database_connection"]
        public: true
        tags: [{ name: contao.hook, hook: isVisibleElement }]
